### ISSUE TITLE
Plan for .vscode gitignore

### ISSUE THREAD

**Issue by gaborszita** [Eaglestrike/2023-RobotCode#4]
Currently, not all files in the `.vscode` directory is gitignored. However, we have talked about that we might have to change this. If someone has their own IDE personal preferences, then he may accidentally commit the file (we saw this action in the last PR) unwillingly creating a potential merge conflict. Now, the problem with gitignoring the whole `.vscode` is that perhaps those files contain important launch information and someone may not be able to launch the code. It worked fine for me, but there may be issues because of this for others. Here's my plan to address this:

1. Gitignore everything in `.vscode`.
2. Create default config files like `settings.json.default` and `launch.json.default`, these will be excluded in the `.gitgnore`.
3. If someone is having issues with compiling/launching/executing/deploying/doing whatever else, then it may be because these IDE config files are not set up correctly. He will just have to copy these default config files and it should fix it (`settings.json.default` -> `settings.json`).
4. To make this copying process a bit less tedious, I can add a shell script for mac/linux and a bat script for Windows to copy these files. `createdefaultconfig.sh` and `createdefaultconfig.bat`.

@SusanC3 What do you think of this?

**Comment by SusanC3** [comment]
Sorry for the late reply, I think this is a very good plan!
